name: Flutter Lint

on:
  pull_request:
    branches: [ "master", "development"]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.2
      - run: flutter --version 

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart analyzer
        run: flutter analyze
